config/routes.rb
Rails.application.routes.draw do
  # root "home#index"
  root "books#index"

  get 'ajax_search_books', to: 'books#ajax_search_books'

  resources :books, only: [:index, :show, :destroy, :new, :create] do
    resources :reviews, only: [:create, :new, :index]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:search].present?
      @books = Book.where("title LIKE ?", "%#{params[:search]}%")
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "#{@book.title} deleted successfully!"
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path, notice: "#{@book.title} created successfully!"
  end

  def ajax_search_books
    # Xử lý sự kiện tìm sách theo title hoặc content
    if params[:search].present?
      @books = Book.where("title LIKE ? OR content LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @books = Book.all
    end

    # Update lại list book với value search
    render json: {
      partial: (render_to_string partial: 'list_book', collection: @books, as: :book, layout: false)
    }
  end

  private

  def book_params
    params.require(:book).permit(:title, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @book = Book.find(params[:book_id])
        @review = Review.new(book_id: params[:book_id], content: params[:content])
        if @review.save
            ActionCable.server.broadcast("review_book_#{@book.id}", { review: @review.content })
        end

    end

    def new
        @review = Review.new
    end

    def index
        @book = Book.find(params[:book_id])
        @reviews = @book.reviews.order(created_at: :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_list_book.html.slim
tr
  td = book.title
  td = book.content
  td = link_to "Detail", book_path(book.id), class: "btn btn-info"
  td = button_to "Delete", book_path(book.id), method: :delete, data: { confirm: "Do you want to delete #{book.title} book?" }, class: "btn btn-danger"

app/views/books/index.html.slim
.container
  .row.justify-content-center
    .col-md-8
      h1 List of Books
      = form_with url: books_path, method: :get, local: true, class: "mb-3" do
        .input-group
          = text_field_tag :search, params[:search], class: "form-control", id: "search-input", data: { url: books_path }, placeholder: "Search book ..."
          = submit_tag "Search", class: "btn btn-primary"

      .table-responsive
        table.table.table-striped
          thead
            tr
              th Title
              th Content
              th
              th
          tbody.list-book-content
            - @books.each do |book|
              = render "books/list_book", book: book
      = link_to "Add Book", new_book_path, class: "btn btn-primary"

app/views/books/new.html.slim
.container
    .row.justify-content-center
        .col-md-8
            h1 Create new Book
            = form_with model: @book, url: books_path, method: :post do |form|
                .form-group
                    = form.label :title
                    = form.text_field :title, class: "form-control"
                .form-group
                    = form.label :content
                    = form.text_area :content, class: "form-control"
                = form.submit "Create", class: "btn btn-success mt-3"

app/views/books/show.html.slim
.container
    .row.justify-content-center
        .col-md-8
            h1 = @book.title
            h3 = @book.content
            #review-book-list data-book-id=@book.id
                = render "reviews/index"
            = render "reviews/new"

app/views/home/index.html.slim
= link_to "Home", root_path, class: "btn btn-primary"

app/views/layouts/_header.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Codecamp</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%# <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Member</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Courses</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Blog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Event</a>
          </li>
        </ul>
      </div> %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Codecamp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_index.html.slim
- @reviews.each do |review|
  p = review.content

app/views/reviews/_new.html.slim
= form_with model: @review, url: book_reviews_path(@book), id: "review-form", method: :post do |form|
  = form.label :content
  = form.text_area :content, id: "input-review", class: "form-control"
  = form.submit "Create", id: "button-submit-review", class: "btn btn-success mt-3"